## Spring boot server config ##
server:
  servlet:
    context-path: /consumer-api/1.0
  port: 9000

spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: consumer
    database-platform: org.hibernate.dialect.PostgreSQLDialect

secrets:
  secretnames: pilot/consumer-api/db
  endpoint: secretsmanager.us-east-1.amazonaws.com
  region: us-east-1